nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://portfolio.antoine-jolivet.fr']
        allow_methods: ['GET']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
